### ISSUE TITLE
impressionListener called multiple times for the same key and attributes

### ISSUE THREAD

**Issue by adriellcardoso** [splitio/react-client#120]
Hi,

Following the [documentation](https://help.split.io/hc/en-us/articles/360038825091-React-SDK#implement-custom-impression-listener) I implemented the impressionListener, but the function was called multiple times for the same key and attributes.

Is that expected? How could I treat this situation to call once by evaluation?

I am trying to send the impression data to the fullstory, but it's necessary call once by session key and attributes or evaluation.

Code:
```
import { SplitFactory } from '@splitsoftware/splitio-react';

const withFeatureFlag = Component => props => {

  ... omit code ...

  function logImpression(impressionData) {
    console.log("splitio Sending impressions", impressionData)
  }

  const [sdkConfig, setSdkConfig] = useState({
    core: {
      authorizationKey: API_KEY,
      key: "anon-1671743490536"
    },
    impressionListener: {
      logImpression
    }
  });

  const [attributes, setAttributes] = useState({});

  useEffect(() => {

    setSdkConfig({
      core: {
        authorizationKey: API_KEY,
        key: "anon-1671743490536"
      }
    });

  }, [authentication.isSignedIn]);

  useEffect(() => {

    setAttributes({
      realm: application.realm ? application.realm.realm : null
    });

  }, [name]);

  return (
    <SplitFactory config={sdkConfig} attributes={attributes} updateOnSdkTimedout>
      <Component {...props } />;
    </SplitFactory>
  );
};
export default withFeatureFlag;
```

The usage code:
```
const App = () => (
    <MyComponents />
);

export default withFeatureFlag(App);

```

Thanks!

**Comment by adriellcardoso** [comment]
Logs
<img width="1072" alt="impressions" src="https://user-images.githubusercontent.com/22645793/209231684-a53b46d4-9831-475b-aae9-69ba85dfecf7.png">

**Comment by agustinona** [comment]
Hi @adriellcardoso,

The impression listener will fire every time a treatment is calculated, which will in turn happen every time a component using that treatment is rendered, so it can happen multiple times for a single feature flag. In order to send only one impression per feature flag per session, you'll need to add logic into your impression listener so that it will keep track of the features that have already been evaluated and send each only once.
