### ISSUE TITLE
Split and segment integration (additional properties)

### ISSUE THREAD

**Issue by dimcsEfisco** [splitio/react-client#226]
Hi! We integrated split with segment (split as a source) https://help.split.io/hc/en-us/articles/360020742532-Segment to check analytics regarding split treatments in segment but faced that there is no way to pass additional parameters to get_treatment event, for example, own property anonymousId and some additional properties (depends on treatment) which very helpful for us to figure out statistics
Is there a way to pass any additional information to the segment via get_treatment event?

The event was fired when getting treatments data
`splitClient.getTreatmentsWithConfig(['treatment_name']);`

**Comment by agustinona** [comment]
Hi @dimcsEfisco it is not possible to enrich the impression data sent using our Segment integration, but you can look into the SDK's [impression listener](https://help.split.io/hc/en-us/articles/360038825091-React-SDK#listener) which you can use to enrich the impression and send it directly to Segment.

**Comment by dimcsEfisco** [comment]
> Hi @dimcsEfisco it is not possible to enrich the impression data sent using our Segment integration, but you can look into the SDK's [impression listener](https://help.split.io/hc/en-us/articles/360038825091-React-SDK#listener) which you can use to enrich the impression and send it directly to Segment.

Hi, thanks. I hope that will help us
