### ISSUE TITLE
Programmatically Set Treatments

### ISSUE THREAD

**Issue by skene** [splitio/react-client#23]
Hello all, 

Is there a way to programmatically set a specific treatment for a given user? So instead of using `useTreatments([])` to receive the calculated treatment a user is going to receive, is it possible to set a specific treatment based on, let's say a URL parameter flag (that we set manually)?

Ultimately, we are trying to split test a home landing page that is located at a subdomain, where our users will then be redirected to our root domain to perform the tracked events (add to cart, purchases, etc). It is unclear to me how these events will know the user came from the subdomain landing page and not the root domain landing page. 

I'm most likely missing something in the docs. 

Thanks,
Skeen

**Comment by skene** [comment]
To make this more clear, is it possible to set our landing page  "promo.domain.com" to be the 'on' treatment of experiment "LandingPage_Test" and our landing page at "domain.com" to be the 'off' treatment for the given experiment?

**Comment by chillaq** [comment]
Hi Spencer, this can be achieved from the Split UI page, by adding a targeting rule with custom attribute "url" and using Regex matcher to serve the desired treatment.
Checkout this KB for a url example: https://help.split.io/hc/en-us/articles/360026231292-Useful-Regex-Examples-for-Targeting

Thanks
Bilal

**Comment by chillaq** [comment]
Hi Spencer, closing this issue, please let us know if you need any more help.

Thanks
Bilal

**Comment by skene** [comment]
sorry for the late response, we were able to figure it out thanks for your help!
