### ISSUE TITLE
Updating the split key

### ISSUE THREAD

**Issue by cbaker** [splitio/react-client#31]
Hello, I'm working on a single-page application where my coworker has implement split to control feature flagging!
We're encountering a problem where when a user first signs in since the split factory has already been rendered once, the client will not update when the configuration updates. This causes a problem as it uses a guest key as the split key until the page is refreshed.

Here's a nonverbatim idea of what we're dealing with

Split Version: 1.1.0
```
    const SplitFactoryWrapper = () => {
        const { user } = useContext(AuthCtx);
        const splitKey = user.email || "guest_user";

        // getSplitConfig just overwrites baseConfig.core.key
        return <SplitFactory config={getSplitConfig(splitKey)}  updateOnSdkUpdate={true}>{children}</SplitFactory>; 
    };
    const App = () => ( <AuthCtx><SplitFactoryWrapper>{children}</SplitFactoryWrapper></AuthCtx> )
```

So the solutions I know that will probably work
1) Delay factory first render until the user is signed-in. (seems hacky as you may truly want to feature flag guest features)
2) Implementing shouldComponentUpdate & componentDidUpdate lifecycle methods to unsubscribe events & create a new factory and client on configuration change in a pull request.
--
3) Refactor code for more appropriate SDK utilization*

* *I don't know if he did or did not implement this ideally, I have limited working experience with Split's SDK.

Let me know what the best course of action would be here,
Thanks!

**Comment by chillaq** [comment]
Hi Chad, React SDK allow multiple client objects using the same Factory instance, it is recommended to use a dummy user key at the initial render, then when we have the actual user key, we can initialize a second client object with the correct user key.

Checkout this KB for more info: https://help.split.io/hc/en-us/articles/360046771911-React-SDK-Lazy-initialization-of-Split-client

Thanks
Bilal

**Comment by cbaker** [comment]
@chillaq Thanks for the response, the documentation you provided doesn't show any usage of the client or factory.

**Comment by chillaq** [comment]
Hi Chad, the KB has an Javascript example of how to initialize multiple user keys with React SDK. Pasted below:
import React, { useState, useEffect } from 'react';
import ReactDOM from 'react-dom';
import { SplitFactory, SplitClient, SplitTreatments } from '@splitsoftware/splitio-react';
import './index.css';
const splitConfig = {
   core: {
      authorizationKey: 'YOUR-API-KEY',
      key: 'anonymous',
   }
}
function MyApp() {
// using 'anonymous' as initial userId
   const [userId, setUserId] = useState(splitConfig.core.key);
// update userId to 'user_id' after 3 seconds
   useEffect(() => {
   setTimeout(() => { setUserId('user_id'); }, 3000);
}, [])
return (
   <SplitTreatments names={['test_split']}>{
   ({ treatments, isReady }) => {
      const evaluation = Is ready: ${isReady}. Treatment value for split "test_split" is: ${treatments.test_split.treatment};
 console.log(evaluation);
 return
 {evaluation}
 }
 });
}

ReactDOM.render(</MyApp>, 
 document.getElementById('root')
);

**Comment by cbaker** [comment]
@chillaq Using the SplitClient component & initializing multiple keys appears to have worked. I do still suggest that the documentation provided gets updated as it doesn't even show usage of the SplitClient component?
