### ISSUE TITLE
Count url not found

### ISSUE THREAD

**Issue by laurib** [splitio/react-client#33]
"@splitsoftware/splitio-react": "1.2.1",
![Screenshot 2020-10-21 at 09 28 40](https://user-images.githubusercontent.com/1352991/96681570-29070680-1380-11eb-9c6b-99b33b01cf2f.png)

I get same problem with 1.2.0. 

I'm using create-react-app with craco.
When i'm using latest versions then i get error: 

```
./node_modules/@splitsoftware/splitio/es/impressions/hasher/hashImpression32.js
Attempted import error: 'buildKey' is not exported from '../../../../../../src'.
```
That is because `buildKey` is imported from '.' and babel-loader compiles it to my root directory. 
If i add `@splitsoftware` to loaderOptions ignore then everything is working except split is starting to make request to this url that does not exist.

Any ideas ?

**Comment by chillaq** [comment]
Hi Lauri, thanks for the info, will repro and get back to you.

Thanks
Bilal

**Comment by chillaq** [comment]
Hi Lauri, could you provide the craco.config.js content for your app?

Thanks
Bilal

**Comment by laurib** [comment]
```
const MomentLocalesPlugin = require('moment-locales-webpack-plugin');

module.exports = function () {
  return {
    typescript: {
      enableTypeChecking: true,
    },
    eslint: {
      mode: 'file',
    },
    babel: {
      plugins: [
        [
          'module-resolver',
          {
            root: ['./src'],
            extensions: ['.js', '.jsx', '.es', '.es6', '.mjs', '.ts', '.tsx'],
          },
        ],
      ],
      loaderOptions: {
        ignore: [/core-js|@splitsoftware/],
        presets: [
          [
            '@babel/preset-env',
            {
              useBuiltIns: 'usage',
              modules: false,
              corejs: {
                version: 3,
                proposals: true,
              },
            },
          ],
        ],
        overrides: [
          {
            test: './node_modules',
            sourceType: 'unambiguous',
          },
        ],
      },
    },
    webpack: {
      plugins: [
        new MomentLocalesPlugin({
          localesToKeep: ['et', 'en'],
        }),
      ],
    },
  };
};

```

**Comment by chillaq** [comment]
Thanks Lauri, checking with the team.

**Comment by NicoZelaya** [comment]
Hi @laurib ! 

Sorry for the long wait but we have version 1.2.2 which should fix this build issue and the endpoint should be available for everyone already. If you can give it a try and let us know how it worked we'll appreciate it. 

I'll go ahead and close the issue but feel free to reopen if you have any further problems with it.

Thanks in advance!
Nico.
