### ISSUE TITLE
SplitTreatments does not set set isReady to true

### ISSUE THREAD

**Issue by Jakst** [splitio/react-client#35]
The `SplitTreatments` component is broken on v1.2.0 and up. As per [this article
](https://help.split.io/hc/en-us/articles/360038825091-React-SDK), you should be able to consume the isReady flag from the render props of this component. However, on v1.2.0 and v.1.2.1 the isReady flag never turns from false to true, leaving our components in a fallback state permanently. 

However, the isReady flag from the `SplitContext` still works fine.

**Comment by chillaq** [comment]
Hi Jakob, isReady is working fine on my end within SplitTreatments block, see example below:

      <SplitTreatments names={[feature_1]} >
        {({ treatments, isReady }) => {
          return isReady ? (
            <div className="App-section">
              <h4>{`Split: ${feature_1}`}</h4>
              <p>{`Treatment value: ${treatments[feature_1].treatment}`}</p>
            </div>
          ) : <Loading />
        }}
      </SplitTreatments>

Could you provide the code that does not work from your side?

Thanks
Bilal

**Comment by Jakst** [comment]
I'll try to work out a minimal reproducible example and come back to you

**Comment by Jakst** [comment]
Turns out this was self inflicted by importing from your internal lib folder, so this little change fixed the problem.

```diff
- import { SplitTreatments } from '@splitsoftware/splitio-react/lib';
+ import { SplitTreatments } from '@splitsoftware/splitio-react'; 
```
