### ISSUE TITLE
Set client key dynamically not working

### ISSUE THREAD

**Issue by ashoksudani** [splitio/react-client#36]
Hi,

We are using react sdk, and trying to set `key` after user is logged in but treatments are not getting updated from component.

Step 1. Initialising sdk with initial config 
```
// where uid = undefined
spliConfig = {
  core: {
    authorizationKey: process.env.SPLIT_IO_KEY,
    key: uid,
    trafficType: 'user',
  }
}

function SplitProvider(splitConfig) {
  return (<SplitFactory config={{splitConfig }}>
      <SplitTreatments names={flagNames}>
    .......
}
```

Step 2. updating `uid` to `1233312312`

But we are not getting updated treatments even after updating configuration with new value of `key` with new user id.

Is there any way we can update splitConfig and get new treatments updated ?

We already whitelisted user `1233312312` in split console.

**Comment by chillaq** [comment]
Hi, In addition to setting the user id, you need to use isReady prop to make sure the SDK download the cache before getting the treatment, otherwise it will always return "control".

See example below, checkout the doc link for more info: https://help.split.io/hc/en-us/articles/360038825091-React-SDK

<SplitTreatments names={[featureName]} >
        {({ treatments, isReady }) => { // Passes down a TreatmentsWithConfig object and SplitContext properties like the boolean `isReady` flag.
          return isReady ?
            this.renderContent(treatments[featureName]) : // Use the treatments and configs.
            <Spinner />; // Render a spinner if the SDK is not ready yet. You can do what you want with this boolean.
        }}
</SplitTreatments>

**Comment by ashoksudani** [comment]
Hi @chillaq 

Thanks for your reply but it did not work.

Here is the log I tried to debug with my following componetn.

```
const DynamicFeatureProvider = ({ getConfig, flagNames, children }) => {
  const config = getConfig();
  console.log('--config---', config);
  return (
    <SplitFactory config={{ ...config }}>
      <SplitTreatments names={flagNames}>
        {(splitProps) => {
          console.log('----****--splitProps.isReady', splitProps.isReady);
          console.log('----****--splitProps.treatments', splitProps.treatments);
          return splitProps.isReady ? (
            <AppComp isReady={splitProps.isReady} features={splitProps.treatments}>
              {children}
            </AppComp>
          ) : (
            'Loading...'
          );
        }}
      </SplitTreatments>
    </SplitFactory>
  );
};
```

But actually Split is not refreshing cache or provides any new treatments when updating `config` parameter in `SplitFactory`

Here is the log, as you can see its getting new config with updated `key` parameter but treatments are never getting updated again.

![Screenshot 2020-11-18 at 3 29 55 PM](https://user-images.githubusercontent.com/552975/99499241-8c9e4700-29b3-11eb-882f-256a06c80481.png)
![Screenshot 2020-11-18 at 3 30 05 PM](https://user-images.githubusercontent.com/552975/99499261-9162fb00-29b3-11eb-823c-513111961b15.png)

**Comment by ashoksudani** [comment]
Just to mention, we are using NextJS to serve this page, is react sdk is compatible with server side rendering as well or it works only for browser single page application?

If not ideal for nextjs, should we use JS sdk for that only then?

**Comment by chillaq** [comment]
Hi @ashoksudani React SDK works only on browser side, does not support server side.
You need to use the npm package for server side.

Using the React SDK, if you like to use another user id, updating config will not work, you need to create new client object from the same factory, checkout this section in our docs: https://help.split.io/hc/en-us/articles/360038825091-React-SDK#advanced-instantiate-multiple-sdk-clients

For pure JS, this is how it is done:
client2 = factory.client(secondUserId);

Thanks
Bilal

**Comment by ashoksudani** [comment]
Thanks @chillaq 

Yes correct, I have tried running as suggested in section with tag `<SplitClient splitKey={this.props.accountId}  >` where splitKey is updated after user is logged in and I could get updated flags when code is running ONLY in browser with DISABLED SSR.

**Comment by chillaq** [comment]
Great, we have plans to add SSR support for React SDK in the future.
