### ISSUE TITLE
Error Handling if Split.io goes down

### ISSUE THREAD

**Issue by Gabxi** [splitio/react-client#43]
Hi,

I went through your SDK https://help.split.io/hc/en-us/articles/360038825091-React-SDK, and I don't see code how to handle if Split.io goes down.

For reference, I was testing and I set the wrong API key. This means the request to Split.io were getting a 404, and the `isReady` variable was never set.

Is there an error variable that can be passed down?

**Comment by chillaq** [comment]
Hi @Gabxi , we try not to raise exceptions or errors in SDK to not to impact production code, if you enable debug SDK log, you will see error logged if there is an issue. 
In general if there is any issue with SDK, it will return "control" when calling getTreatment(), this indicates something is not right, either with SDK cache, network connection or config settings.

Hope that helps.

Thanks
Bilal

**Comment by Gabxi** [comment]
Ah thanks, is there sample React code to show how to get the control?

**Comment by chillaq** [comment]
Simply fetch the <Treatment> element with incorrect API Key, or incorrect Split name, or using Chrome Dev to block network calls, you will see "control" returned.
