### ISSUE TITLE
Function returned by useTrack is recreated on every render

### ISSUE THREAD

**Issue by roy-dendro** [splitio/react-client#53]
Hi there, first of all thanks for creating and maintaining this codebase!

In my code-base i create a custom hook that basically looks like this (simplified)

```js
import {useTrack } from '@splitsoftware/splitio-react'

const useExperimentTrack = () => {
    const track = useTrack()

    // some other logic

    return useCallback(
        (event) => {

            // some logic to add data to the event

            // track event to split queue
            track(event)

          // do some other stuff
        },
        [track]
    )
}
```

I deliberately use `useCallback` in order to not unnecessarily recreate the function and, so i can use it as a dependency in useEffect in other places in the code and trust its not triggered.

Something like this very contrived example, where i would expect the useEffect to only trigger when `isImportantBoolean` changes.

```
import React from 'react'
import { useTaskEventTracking } from './useTaskEventTracking'

const Example = () => {
    const [isImportantBoolean, setIsImportantBoolean] = React.useState(false)
    const { trackTaskEvent } = useTaskEventTracking()

    React.useEffect(() => {
        if (isImportantBoolean) {
            trackTaskEvent({'magic':' 'has happened')
        }
    }, [trackTaskEvent, isImportantBoolean])

    return (
        <div>
            <button onClick={() => setIsImportantBoolean(!isImportantBoolean)}>
                rererender
            </button>
        </div>
    )
}

export default Example
```

My issue is that in `useTrack`([here](https://github.com/splitio/react-client/blob/master/src/useTrack.ts)), the function is (i think) always recreated and thus the function in my custom hook is always recreated and thus the useEffect in the Example component triggers on every re-render.

I'm not 100% familiar with the inner workings of the split client but do you think it would be possible to change the code in such a way that the function is not always recreated?

Maybe something like:
```
const useTrack = (key, trafficType) => {
  const client = checkHooks(ERROR_UTRACK_NO_USECONTEXT) ? useClient(key, trafficType) : null;
  return React.useCallback(()=> client ? client.track.bind(client) : noOpFalse,[client]);
};
```

Any other suggestions would be appreciated as well!

**Comment by chillaq** [comment]
Hi @roy-dendro , You are right, the function is getting recreated, as its not an object or interface that stays alive and allow to send events, its simply a function of client interface (client.track()), so it is called only once.

Would this change work?

const useExperimentTrack = () => {
    return useCallback(
        (event) => {
            // track event to split queue
             const track = useTrack()
            track(event)
        },
        [track]
    )
}

**Comment by chillaq** [comment]
Hi @roy-dendro , I am closing out this issue. If there is still an open issue or if we can be of further assistance on this topic, feel free to respond and re-open it.

Thanks
Bilal
