### ISSUE TITLE
WebSocket error when pages are refreshed in Firefox  

### ISSUE THREAD

**Issue by jbadavis** [splitio/react-client#71]
### Summary

When refreshing a page wrapped in the `SplitFactory` provider in Firefox an error is logged to the console:

```
The connection to https://streaming.split.io/sse... was interrupted while the page was loading. 
```

There appear to be Firefox specific WebSocket requirements that aren't being covered by the library:

https://bugzilla.mozilla.org/show_bug.cgi?id=712329

Some similar issues:

- [socket.io](https://github.com/socketio/socket.io/issues/2016)
- [kubeapps](https://github.com/kubeapps/kubeapps/pull/2267)

### Environment

Yarn: 1.22.11
Node: 14.17.4
React: 16.13.1
@stripe/react-stripe-js: 1.4.1
Firefox: 91.0.2

**Comment by chillaq** [comment]
Hi @jbadavis , thanks for the info, I see the issue on my side as well, will check with the team.

Thanks
Bilal
