### ISSUE TITLE
Using split for user who are not logged in?

### ISSUE THREAD

**Issue by aibrahim3546** [splitio/react-client#79]
From what i read the `key` is required and it must be unique key.

In my case, I want to use the split even when my user are not logged in or when new user signing up?

How can i achieve that since this user will not have a unique key?

**Comment by chillaq** [comment]
Hi @aibrahim3546, You can generate an anonymous id and store it in a cookie to be re-used on the same machine every time the page is opened while no user is logged in.

We do have some material on using anonymous id in experiments, checkout links below:
https://help.split.io/hc/en-us/articles/360029915831-Experimenting-with-anonymous-and-logged-in-users
https://help.split.io/hc/en-us/articles/360029915971-Consistent-experience-from-anonymous-to-logged-In
https://help.split.io/hc/en-us/articles/360035494011-Successfully-Experiment-with-Anonymous-and-Logged-in-Users

Thanks
Bilal

**Comment by aibrahim3546** [comment]
Noted. I taught if I don't pass the `key` splitio will automatically assign a **anonymousId** from their side.

It would be nice if splitio can assign **anonymousId** if key is not passed, just like how [segment](https://segment.com/) is doing. Thanks Bilal.
