### ISSUE TITLE
CORS issue

### ISSUE THREAD

**Issue by rhdhvolschenk** [splitio/react-client#87]
I am getting CORS issues while using this package in our application.
All requests just throw this error:

> Access to fetch at 'https://sdk.split.io/api/mySegments/xxx' from origin 'https://xxx.abc' has been blocked by CORS policy: Request header field traceparent is not allowed by Access-Control-Allow-Headers in preflight response.

How do I go about sorting this out?

**Comment by chillaq** [comment]
Hi @rhdhvolschenk, can you provide the code that uses the SDK? Also are you using Angular with Service Workers?
Also, please provide HAR file for all network calls (you can right-click in Network tab from Chrome dev console).

Thanks
Bilal

**Comment by rhdhvolschenk** [comment]
> can you provide the code that uses the SDK?

I cannot provide access to the code, but I will provide the relevant snippet(s) here.

_A shared provider creator_:

```tsx
// shared/FeatureFlagsProvider.tsx
import { SplitFactory } from '@splitsoftware/splitio-react';
import { ISplitFactoryChildProps } from '@splitsoftware/splitio-react/types/types';
import React from 'react';

import Loader from '../../components/Loader';

interface FeatureFlagsProviderProps {
	splitioAuthorizationKey: SplitIO.IBrowserSettings['core']['authorizationKey'];
	splitioFeaturesMock: SplitIO.IBrowserSettings['features'];
	splitioKey: SplitIO.IBrowserSettings['core']['key'];
}

const FeatureFlagsProvider: React.FC<FeatureFlagsProviderProps> = ({
	children,
	splitioAuthorizationKey,
	splitioFeaturesMock,
	splitioKey,
}) => {
	const sdkConfig: SplitIO.IBrowserSettings = React.useMemo(
		() => ({
			core: {
				authorizationKey: splitioAuthorizationKey,
				key: splitioKey,
			},
			features: splitioFeaturesMock,
			startup: {
				readyTimeout: 5,
				retriesOnFailureBeforeReady: 1,
			},
		}),
		[splitioAuthorizationKey, splitioKey],
	);

	return (
		<SplitFactory config={sdkConfig}>
			{({ isReady }: ISplitFactoryChildProps) => {
				if (!isReady) {
					return <Loader />;
				}
				return <>{children}</>;
			}}
		</SplitFactory>
	);
};

export default FeatureFlagsProvider;
```

_A single instance of the provider (using the creator above)_:

```tsx
// providers/FeatureFlags.tsx
import React from 'react';

import { SPLITIO_AUTHORIZATION_KEY } from '@/constants';
import { nullUser, UserContext } from '@/providers/AuthProvider/AuthenticatedUserContext';
import { FeatureFlagsProvider } from '@/shared/FeatureFlagsProvider.tsx';

const FeatureFlags: React.FC = ({ children }) => {
	const user = React.useContext(UserContext);

	return (
		<FeatureFlagsProvider
			splitioAuthorizationKey={SPLITIO_AUTHORIZATION_KEY}
			splitioFeaturesMock={{}}
			splitioKey={user.id}
		>
			{children}
		</FeatureFlagsProvider>
	);
};

export default FeatureFlags;
```

The application then gets wrapped in the implementation created above.

> Also are you using Angular with Service Workers?

No, the React SDK as shown above.

> Also, please provide HAR file for all network calls (you can right-click in Network tab from Chrome dev console).

I will only be able to do so tomorrow, I removed the client momentarily to restore access to our application for our users.
I will try and recreate this locally in the morning (I think `NODE_ENV=production` has something to do with it in my case)
and then send through the relevant network calls.

**Comment by rhdhvolschenk** [comment]
It took a bit longer to generate the `.har` file for you, the system was in use during the day: 
[kes.rhdhv.io.har.zip](https://github.com/splitio/react-client/files/8181236/kes.rhdhv.io.har.zip).

I tried my utmost to recreate this behaviour on my local machine but truly could not.

I am quite confused as to why this is happening on this *one* environment only,
we have a few applications running in the same manner and they all function properly.

**Comment by chillaq** [comment]
Hi @rhdhvolschenk , looks like the allow origin header is being overwritten, see below:
access-control-allow-origin: https://kes.rhdhv.io

Usually the split cloud set this header to 
access-control-allow-origin: *

Which why calls to *.split.io domain are blocked.

Maybe there is a network proxy that is replacing this response header.

**Comment by rhdhvolschenk** [comment]
I am a bit confused.
That is a **response** header. My server would not be controlling the response headers, right?
Am I misunderstanding?

**Comment by rhdhvolschenk** [comment]
Update. After digging through all other settings, I found the culprit.
It turns out that _Microsoft Application Insights_ messes with the headers.
Sorry for wasting your time, and thanks for taking a look regardless.

**Comment by chillaq** [comment]
Great, thanks

**Comment by domshyra** [comment]
@rhdhvolschenk could you elaborate on this. I am having this error to with a index.js like so 

``` javascript
import App from "./App";
import { AppInsightsContext } from "@microsoft/applicationinsights-react-js";
import { BrowserRouter } from "react-router-dom";
import { MsalProvider } from "@azure/msal-react";
import { PublicClientApplication } from "@azure/msal-browser";
import React from "react";
import ReactDOM from "react-dom";
import { Provider as ReduxProvider } from "react-redux";
import { SplitFactory } from "@splitsoftware/splitio-react";
import configureStore from "./redux/configureStore";
import { getAppInsightsReactPlugin } from "./applicationInsights";
import { msalConfig } from "./components/Configuration/authConfig";
import { sdkConfig } from "./components/Configuration/Config";

const store = configureStore();

const msalInstance = new PublicClientApplication(msalConfig);

const baseUrl = document.getElementsByTagName("base")[0].getAttribute("href");
const rootElement = document.getElementById("root");
const reactPlugin = getAppInsightsReactPlugin();

ReactDOM.render(
	<SplitFactory config={sdkConfig} updateOnSdkTimedout={true}>
		<BrowserRouter basename={baseUrl}>
			<ReduxProvider store={store}>
				<MsalProvider instance={msalInstance}>
					<AppInsightsContext.Provider value={reactPlugin}>
						<App />
					</AppInsightsContext.Provider>
				</MsalProvider>
			</ReduxProvider>
		</BrowserRouter>
	</SplitFactory>,
	rootElement
);
```

my sdkConfig is like so. I have my key as User currently since I am just trying to get this to work with a simple flag that has no configs and we have no segments 
````  javascript
// Create the config for the SDK factory.
export const sdkConfig = {
	core: {
		authorizationKey: "client-api-key",
		key: "User"
	},
};
```


some errors are:
Access to fetch at 'https://sdk.split.io/api/mySegments/User' from origin 'https://localhost:44333' has been blocked by CORS policy: Request header field traceparent is not allowed by Access-Control-Allow-Headers in preflight response. 

Access to fetch at 'https://auth.split.io/api/v2/auth?users=User' from origin 'https://localhost:44333' has been blocked by CORS policy: Request header field traceparent is not allowed by Access-Control-Allow-Headers in preflight response.

https://auth.split.io/api/v2/auth?users=User returns "missing auth"

**Comment by rhdhvolschenk** [comment]
Hey @domshyra, sure thing.

We are using _Microsoft Application Insights_, and I had to let `split.io` through for the strange headers to not get added:

```ts
import { ApplicationInsights, DistributedTracingModes } from '@microsoft/applicationinsights-web';

export const loadAppInsights = (
	connectionString: string,
): ApplicationInsights | undefined => {
	const appInsights = new ApplicationInsights({
		config: {
			connectionString,
			disableFetchTracking: false,
			enableCorsCorrelation: true,
			enableRequestHeaderTracking: true,
			enableResponseHeaderTracking: true,
			distributedTracingMode: DistributedTracingModes.W3C,
			enableAutoRouteTracking: true,
			autoTrackPageVisitTime: true,
			enableUnhandledPromiseRejectionTracking: true,
			correlationHeaderExcludedDomains: ['*.auth0.com', '*.split.io'], // THIS LINE
		},
	});

	appInsights.loadAppInsights();
	appInsights.trackPageView();
	return appInsights;
};
```
