### ISSUE TITLE
There was a problem configuring the storybook project

### ISSUE THREAD

**Issue by sunfulin123** [splitio/react-client#97]
Hi✋,I have some problem need to help
When I introduced `@splitsoftware/splitio-react` into storybook, I add .storybook/preview file. `decorators` are configured in JS. 
```
#preview.js
const MainDecorator = story => {
  return (
    <SplitFactory config={splitConfiguration()}>
      <CobaltRoot>{story()}</CobaltRoot>
    </SplitFactory>
  )
}
export const decorators = [MainDecorator]
```
![image](https://user-images.githubusercontent.com/89896876/169240167-11e8a62f-0053-44f2-ba2a-ed8f28807414.png)
When I switch pages, storybook will update the decorators every time I switch pages, and the data will be restored from on to control. 
![image](https://user-images.githubusercontent.com/89896876/169240377-3140fce0-0930-446c-97ab-8b11bc3caa98.png)
![wecom-temp-db7aacc876bd2127c453c5da16775fb6](https://user-images.githubusercontent.com/89896876/169237641-9d9f9c19-842b-435c-9d89-f664b23d6909.png)
![image](https://user-images.githubusercontent.com/89896876/169237773-2521d9f8-60de-49da-acdf-7b9de140e898.png)
![wecom-temp-c64762736b272883eda3bc48513933ff](https://user-images.githubusercontent.com/89896876/169237830-52a510f9-9927-43a3-b3e3-652cfa245a4a.png)

I found it in `@splitsoftware/split-react/es/split/services/splitChanges/offline/browser.js`, the first data is always cached, As a result, `mockupdated` returns false after the second time, which makes my page unable to display correctly
Do you have any good attention？Thank you very much

**Comment by sunfulin123** [comment]
hi @chillaq，This is my log
Log when the page is initialized
[localhost-log-1653365995349.log](https://github.com/splitio/react-client/files/8759542/localhost-log-1653365995349.log)
![image](https://user-images.githubusercontent.com/89896876/169952314-8c53b96e-dcc7-4811-8d74-958af27bab0a.png)

When switching page logs
[localhost-log-change-page-1653366131485.log](https://github.com/splitio/react-client/files/8759543/localhost-log-change-page-1653366131485.log)
![image](https://user-images.githubusercontent.com/89896876/169952157-33cbdd69-3685-4cd7-9817-1bdd082f4972.png)

**Comment by chillaq** [comment]
Hi @sunfulin123, Both logs show there are no checking of "isReady" prop, as shown in my example, you do need to make sure the SDK is ready, meaning all information is downloaded to its cache before fetching the treatment.

Another issue is to set the factory parameter storage.type to "LOCALSTORAGE". This will store the SDK cache in the browser file system, which means the second factory instance will re-use the same cache and will be ready much faster.

Hope that helps.

Thanks

**Comment by sunfulin123** [comment]
Thank you very much for help，I will try

**Comment by chillaq** [comment]
Hi @sunfulin123 , I am closing this issue, let us know if you need any further help.

Thanks
